// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgnEMqtkfeEZzQSTY5UlK6TsacbxiL0II',
    appId: '1:935744152330:web:27bb9238e5499026ee10f3',
    messagingSenderId: '935744152330',
    projectId: 'giggre-prod',
    authDomain: 'giggre-prod.firebaseapp.com',
    storageBucket: 'giggre-prod.firebasestorage.app',
    measurementId: 'G-ZS5XGGSSNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRLtNaXb6zZzN0v8y_qY-JA3qci5fzomQ',
    appId: '1:935744152330:android:906c6f70fa38c3e3ee10f3',
    messagingSenderId: '935744152330',
    projectId: 'giggre-prod',
    storageBucket: 'giggre-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8G-pI4L1N2Dam2fw9CbK05n_JcGdcMo',
    appId: '1:770115931871:ios:6e268a217b93cbfb1de36a',
    messagingSenderId: '935744152330',
    projectId: 'giggre-prod',
    storageBucket: 'giggre-prod.firebasestorage.app',
    iosClientId:
        '770115931871-4n5bcq4h4209ev8n7s28nb24jcuht4gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.giggreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu8G-pI4L1N2Dam2fw9CbK05n_JcGdcMo',
    appId: '1:770115931871:ios:6e268a217b93cbfb1de36a',
    messagingSenderId: '935744152330',
    projectId: 'giggre-prod',
    storageBucket: 'giggre-prod.firebasestorage.app',
    iosClientId:
        '770115931871-4n5bcq4h4209ev8n7s28nb24jcuht4gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.giggreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgnEMqtkfeEZzQSTY5UlK6TsacbxiL0II',
    appId: '1:935744152330:web:27bb9238e5499026ee10f3',
    messagingSenderId: '935744152330',
    projectId: 'giggre-prod',
    authDomain: 'giggre-prod.firebaseapp.com',
    storageBucket: 'giggre-prod.firebasestorage.app',
    measurementId: 'G-ZS5XGGSSNN',
  );
}
