// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUiwYLiHhU8EutBBjJBKNm8DzCBi7-tc',
    appId: '1:770115931871:web:73f8865d8126903a1de36a',
    messagingSenderId: '770115931871',
    projectId: 'simpleproject-8ff7a',
    authDomain: 'simpleproject-8ff7a.firebaseapp.com',
    storageBucket: 'simpleproject-8ff7a.firebasestorage.app',
    measurementId: 'G-06F6TFK5KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcH5L5HN3OiUX9Klm0VDc3RiOTPWznw0',
    appId: '1:770115931871:android:40d6b552fe1652791de36a',
    messagingSenderId: '770115931871',
    projectId: 'simpleproject-8ff7a',
    storageBucket: 'simpleproject-8ff7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8G-pI4L1N2Dam2fw9CbK05n_JcGdcMo',
    appId: '1:770115931871:ios:6e268a217b93cbfb1de36a',
    messagingSenderId: '770115931871',
    projectId: 'simpleproject-8ff7a',
    storageBucket: 'simpleproject-8ff7a.firebasestorage.app',
    iosClientId: '770115931871-4n5bcq4h4209ev8n7s28nb24jcuht4gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.giggreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu8G-pI4L1N2Dam2fw9CbK05n_JcGdcMo',
    appId: '1:770115931871:ios:6e268a217b93cbfb1de36a',
    messagingSenderId: '770115931871',
    projectId: 'simpleproject-8ff7a',
    storageBucket: 'simpleproject-8ff7a.firebasestorage.app',
    iosClientId: '770115931871-4n5bcq4h4209ev8n7s28nb24jcuht4gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.giggreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoUiwYLiHhU8EutBBjJBKNm8DzCBi7-tc',
    appId: '1:770115931871:web:78b42c9d11ff04371de36a',
    messagingSenderId: '770115931871',
    projectId: 'simpleproject-8ff7a',
    authDomain: 'simpleproject-8ff7a.firebaseapp.com',
    storageBucket: 'simpleproject-8ff7a.firebasestorage.app',
    measurementId: 'G-NTGCN6WKB1',
  );
}
